### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by comfirmedrecreate** [BrotherSothoth/Boredless-Tourist#1]
It's simply a mess there's so much rewording and better ways to handle this it's like if I taught my 5 year old python.

**Comment by BrotherSothoth** [comment]
> It's simply a mess there's so much rewording and better ways to handle this it's like if I taught my 5 year old python.

Good for you, please tell yourself that if it makes you feel better. Pretty sure my python skills were around that of a 5 year old when I wrote this years ago. I'm just uploading really old code to GitHub as a store for now, even though I've been busy lately. No need to search around for random code on GitHub to shit on.
